### ISSUE TITLE
Warning: Undefined array key

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/openai#23]
I'm getting this error when I try to use the module. I don't think this error is fatal, but I'm getting those too.

`Warning: Undefined array key "openai_tone_edit" in openai_content_entity_adjust_tone() (line 258 of /var/www/html/modules/openai/modules/openai_content/openai_content.module).`

**Comment by stpaultim** [comment]
I was having trouble connecting to OpenAI. It said my key was wrong, so I tried to delete the key and got a fatal error. Site is now unusable. 

![image](https://github.com/user-attachments/assets/b413ded2-ad53-4275-bfd2-e7290ead0c3e)

Error message
Warning: Undefined array key "key_provider" in key_get_key_value() (line 665 of /var/www/html/modules/key/key.module).
Warning: Undefined array key "plugin module" in plugin_manager_get_function() (line 746 of /var/www/html/modules/plugin_manager/includes/plugins.inc).
Warning: Undefined array key "plugin type" in plugin_manager_get_function() (line 746 of /var/www/html/modules/plugin_manager/includes/plugins.inc).
Warning: Undefined array key "path" in plugin_manager_get_function() (line 748 of /var/www/html/modules/plugin_manager/includes/plugins.inc).
Warning: Array to string conversion in plugin_manager_get_function() (line 748 of /var/www/html/modules/plugin_manager/includes/plugins.inc).
Warning: require_once(/var/www/html//Array): Failed to open stream: No such file or directory in require_once() (line 748 of /var/www/html/modules/plugin_manager/includes/plugins.inc).
Error: Failed opening required '/var/www/html//Array' (include_path='.:/usr/share/php') in plugin_manager_get_function() (line 748 of /var/www/html/modules/plugin_manager/includes/plugins.inc).
[Dismiss](https://aitest.ddev.site/admin/modules/list#)
Failed opening required '/var/www/html//Array' (include_path='.:/usr/share/php')

**Comment by keiserjb** [comment]
I'm concerned about this.  Were you using a file or configuration with the key module?

**Comment by stpaultim** [comment]
I was using configuration with Key module. Because, I'm a bit unsure how to use file - and didn't really try.

**Comment by keiserjb** [comment]
I think this is all related to the key getting truncated during the key module setup.

**Comment by keiserjb** [comment]
https://github.com/backdrop-contrib/key/issues/3

**Comment by keiserjb** [comment]
This seems to resolve itself if the keys function correctly.
