### ISSUE TITLE
Make sure module works with newer key format

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/openai#25]
> OpenAI has transitioned from legacy API keys to a more structured system involving project-based API keys. While legacy keys are still functional for existing setups, OpenAI recommends generating new keys within the project framework for enhanced management and security.

Legacy keys start with `sk-`
New keys start with `sk-proj-`

It seems as if it's impossible to generate a new legacy key at this time. So, it is possible, that only folks with legacy keys are able to use this module at this time.

**Comment by keiserjb** [comment]
I'm pretty sure it's not OpenAI but actually the Key module that is truncating the longer API keys.

**Comment by stpaultim** [comment]
OK. When I create a new key, the module does not work. 

But, when I found this link to the LEGACY API dashboard on my account, I was also able to create a new legacy key - and now the module is working. 

https://platform.openai.com/settings/profile/api-keys

I'm still getting a few errors that I will report, but overall I'm able to connect with OPEN AI and at least do some things. 

Despite the problems I've had, it's pretty exciting.

@keiserjb

**Comment by keiserjb** [comment]
I'm going to close this issue since we've resolved the problem in the key module.

**Comment by keiserjb** [comment]
I'm going to close this issue since we've resolved the problem in the key module.
