### ISSUE TITLE
Warning: Undefined array key "storage"

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/openai#26]
I'm currently using a legacy API key.

I went here to ask a question: https://----.ddev.site/admin/config/openai/chatgpt

I'm getting this error:

> Warning: Undefined array key "storage" in openai_chatgpt_form_submit() (line 192 of /var/www/html/modules/openai/modules/openai_chatgpt/openai_chatgpt.module).

![image](https://github.com/user-attachments/assets/2b300bf6-4e38-4564-8949-3fa8f081b9eb)

So, it did work and it did answer my question. But, it through a scary looking error in the process. 

:-)

**Comment by stpaultim** [comment]
Today, after starting over with updated version of Key module and an updated API Key. I'm still getting this error, when I got to:

/admin/config/openai/chatgpt

This time, I have ONLY enabled the core OpenAI module and the ChatGPT Explorer module.

I am still using configuration for the Key module. I will try switching to file.

**Comment by stpaultim** [comment]
Also got this error while trying the "adjust tone" option on a node. Found this while doing a screenshare with @keiserjb. 

Seems related. Will leave this here, until we find a reason to spin this off into a different issue.

```
Warning: Undefined array key "openai_tone_edit" in openai_content_entity_adjust_tone() (line 258 of /var/www/html/modules/openai/modules/openai_content/openai_content.module).
Warning: Trying to access array offset on null in openai_content_entity_adjust_tone() (line 258 of /var/www/html/modules/openai/modules/openai_content/openai_content.module).
```

Again, these warnings do not prevent the module for executing it's task. But, they look a bit scary.

**Comment by keiserjb** [comment]
I think the pr fixes it.
