### ISSUE TITLE
User error: Composer detected issues in your platform

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/openai#30]
I tried installing OpenAI on a Backdrop CMS Demo site and I'm getting a very new error here. 

Just by accessing the OpenAI configuration page, I'm getting this error in the log:

`
User error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.30. in require() (line 24 of /var/lib/tugboat/backdrop/modules/openai/vendor/composer/platform_check.php).
`

Steps To Reproduce:

1) Spin up Demo site on BackdropCMS.org
2) Enable OpenAI module and required modules (Key)
3) Create a key for OpenAI API Key
4) Create a key for OpenAI OrgID
5) Go to `/admin/config/openai/settings`and select OrgID for "Organization ID" 
6) Check logs and find the above error.

Site is using PHP Version: 8.1.30 - as indicated in the error.

Locally, I've been tesing in DDEV with PHP Version: 8.3.14 and not seeing this error.

Does this module really require 8.2 or is this because of code carried over from Modern Drupal?

**Comment by keiserjb** [comment]
What version of php were you using?  Things did not break for me using php 8.1 but they definitely did on php 8.0.  The [OpenAI Php Client](https://github.com/openai-php/client), included in the module requires php 8.1.  It is possible another dependency pulled in a php 8.2 requirement.

**Comment by stpaultim** [comment]
> What version of php were you using?

I mentioned in the original description that I got this error using a BackdropCMS demo site that is running PHP 8.1.30. 

In my local tests, I am running 8.3.14 and have NOT seen this error there.

I reproduced this error on two different Backdropcms.org DEMO sites.

**Comment by keiserjb** [comment]
I think I found a reason why this was happening.  I made a couple of changes to the composer file.

```
{
    "name": "backdrop/openai",
    "description": "A set of modules to enable OpenAI integration with Backdrop and augment the content experience with AI-assisted tools.",
    "keywords": ["openai", "GPT-3", "DALL-E", "content generation", "AI", "artificial intelligence"],
    "type": "project",
    "license": "GPL-2.0-or-later",
    "authors": [
        {
            "name": "Justin Keiser",
            "homepage": "https://keiserjb.com",
            "role": "Maintainer"
        }
    ],
    "require": {
        "php": ">=8.1",
        "openai-php/client": ">=v0.7.8",
        "guzzlehttp/guzzle": "^7.9",
        "guzzlehttp/psr7": "^2.7",
        "symfony/http-client": "^6.4",
        "nyholm/psr7": "^1.8"
    },
    "config": {
        "platform": {
            "php": "8.1"
        },
        "allow-plugins": {
            "php-http/discovery": true,
            "composer/installers": true
        },
        "optimize-autoloader": true,
        "preferred-install": "dist"
    }
}
```

The previous version required 

"symfony/http-client": "^7.1",

which has a dependency for php 8.2.
